force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Product Informations</relationshipLabel>
    <relationshipName>Product_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Informations</relationshipLabel>
    <relationshipName>Product_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Replacement_Text__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Text__c</fullName>
    <label>Replacement Text</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Free</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInformation.cls
global class ProductInformation {
    /*
Purpose			: This is a Model to contain the Product_Information__c records in a model way to provide a encapsulation on main object record.
Author			: Ashutosh Pathak
Created Date	: 15 June 2021
Created For		: N26 Case Study
Version			: 1: Initial Draft 
*/
    @AuraEnabled
    public String productTypeCategory{get;set;}
    @AuraEnabled
    public String productName{get;set;}
    @AuraEnabled
    public String productId{get;set;}
    @AuraEnabled
    public String countryName{get;set;}
    @AuraEnabled
    public String currencyISOCode{get;set;}
    @AuraEnabled
    public decimal amount{get;set;}
    @AuraEnabled
    public decimal percentage{get;set;}
    @AuraEnabled
    public String productValueWhenAmountPercentageIsNull{get;set;}
    @AuraEnabled
    public Boolean isAmount{get{return amount != null;}}
    @AuraEnabled
    public Boolean isPercentage{get{return percentage != null;}}
    
    public ProductInformation(){}
    public List<ProductInformation> getProductInfoModel(List<Product_Information__c> prodInfos){
        List<ProductInformation> result = new List<ProductInformation>();
        if(prodInfos == null || prodInfos.isEmpty())
            return result;
        for(Product_Information__c prodInfo: prodInfos){
            ProductInformation obj = new ProductInformation();
            obj.amount = prodInfo.Amount__c;
            obj.percentage = prodInfo.Percentage__c;
            obj.countryName = prodInfo.Country__r.Name;
            obj.currencyISOCode = prodInfo.CurrencyISOCode;
            obj.productId = prodInfo.Product__c;
            obj.productName = prodInfo.Product__r.Name;
            obj.productTypeCategory = prodInfo.RecordType.Name;
            obj.productValueWhenAmountPercentageIsNull = prodInfo.Replacement_Text__c;
            result.add(obj);
        }
        return result;
    }
}