force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Product Informations</relationshipLabel>
    <relationshipName>Product_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Informations</relationshipLabel>
    <relationshipName>Product_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Replacement_Text__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Text__c</fullName>
    <label>Replacement Text</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Free</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInformationSelector.cls
public class ProductInformationSelector {
    /*
    Purpose			: This is a class following the selector pattern so that all the DB retrieval queries can be stored here for Product_Information__c object.
    Author			: Ashutosh Pathak
    Created Date	: 15 June 2021
	Created For		: N26 Case Study
    Version			: 1: Initial Draft 
    */
    static LoggingUtils logger = new LoggingUtils('ProductInformationSelector');
    
    public static String fields = 'Country__c, Country__r.Name, Product__c, Product__r.Name, Replacement_Text__c, Amount__c, Percentage__c, CurrencyIsoCode, RecordTypeId, RecordType.Name, Id';
    public static List<Product_Information__c> getRecordsByCountryAndProduct(String country, String productName){
        String query = generateSelectClause() + ' WHERE Country__r.Name=:country AND Product__r.Name=:productName WITH SECURITY_ENFORCED';
        logger.log(LoggingUtils.LogType.DEBUG, query, null, false);
        List<Product_Information__c> result = (List<Product_Information__c>)Database.query(query);
        return result;
    }
    
    private static String generateSelectClause(){
        return 'SELECT '+fields+' FROM '+Constants.ProductInformation.ObjectName;
    }
}