force-app/main/default/objects/Contact/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Informations</relationshipLabel>
    <relationshipName>Product_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactsSelector.cls
public class ContactsSelector {
	/*
    Purpose			: This is a class following the selector pattern so that all the DB retrieval queries can be stored here for Product_Information__c object.
    Author			: Ashutosh Pathak
    Created Date	: 15 June 2021
	Created For		: N26 Case Study
    Version			: 1: Initial Draft 
    */
    static LoggingUtils logger = new LoggingUtils('ContactsSelector');
    
    public static String fields = 'Home_Country__c, Product__c, Name, Unique_Identifier__c, Id';
    public static Contact getRecordByUniqueIdentifier(String uniqueId){
        String query = generateSelectClause() + ' WHERE Unique_Identifier__c =:uniqueId';
        logger.log(LoggingUtils.LogType.DEBUG, query, null, false);
        List<Contact> results = (List<Contact>)Database.query(query);
        Contact result = results == null || results.isEmpty() ? null : results[0];
        system.debug('##result: '+result);
        return result;
    }
    
    private static String generateSelectClause(){
        return 'SELECT '+fields+' FROM '+Constants.Contact.ObjectName;
    }
}